trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK'
  inputs:
    version: '8.0.x'
    includePreviewVersions: true 
- task: PowerShell@2
  displayName: 'Install MAUI'
  inputs:
    targetType: 'inline'
    script: 'dotnet workload install maui'

- task: PowerShell@2
  displayName: 'Restore packages'
  inputs:
    targetType: 'inline'
    script: 'dotnet restore $(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'