# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 8.0'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'


- script: |
    dotnet workload install maui-android
  displayName: 'Install .NET MAUI workload'
  # This will install the latest stable version of the required workload.

# - task: DotNetCoreCLI@2
#  inputs:
#    command: 'restore'
#    projects: '**/*.csproj'


- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/SchoolSystem.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/SchoolSystem.sln'
    arguments: '--configuration $(buildConfiguration) --no-build'
